---
title: "week5"
author: Jiajun Li
output:
  beamer_presentation:
    theme: "Copenhagen"
    colortheme: "rose"
bibliography: term2.bib
date: "2026-06-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# What I did

- Faced with the OneDrive sync issue again. It was resolved after trying to reinstall OneDrive once more, but I am not sure if the problem will happen again.

- Finished the presentation slides.

- Reformed the codes, now all codes for my plots are located in plots.ipynb.

- setting up the models, still debugging.

# Grid settings
\tiny
```{python, eval = FALSE}
#Logistic Regression
grid_lr = {
    'C': [0.01, 0.1, 1, 10], 
    'penalty': ['L1','l2']
}
lr_clf = LogisticRegression(random_state=SEED)



# Classification Trees
grid_dt = {
    'max_depth': [5, 10, 15, 20, None], 
    'min_samples_leaf': [1, 2, 5, 10], 
    'min_samples_split': [2, 5, 10] 
}
dt_clf = DecisionTreeClassifier(random_state=SEED)


#XGBoost
grid_xgb = {
    'learning_rate': [0.05, 0.1, 0.2], 
    'n_estimators': [100, 250, 500], 
    'max_depth': [4, 6, 8], 
    'colsample_bytree': [0.6, 0.8, 1.0]     
}
xgb_clf = XGBClassifier( eval_metric='logloss', random_state=SEED, enable_categorical=True)
```

# Plan for next week
- Attempt to resolve the current model training error; I believe I can fix it on my own.
- Model tuning and evaluating
- Try to fix the OneDrive issue (if it actually happens again)
- Continue writing the report

# Question
If I am truly unable to resolve the OneDrive issue and it cannot maintain a full version history of my progress, would it be acceptable to manually save my files locally and upload them together as a zip file when submitting the assignment?
